# -*- coding: utf-8 -*-
"""SISTEM REKOMENDASI FATHUL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fOiJussXWseWVAth7OAC2IA6JvJCiRrl

##IMPORT DATASET DARI KAGGLE
"""

from google.colab import files
files.upload()

"""##UNDUH DATASET"""

!pip install -q kaggle

# 2. Buat direktori kaggle dan pindahkan file json ke sana
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json
!kaggle datasets download -d adityakammati/fashion-recomendation-dataset

"""##UNZIO DATASET"""

!unzip -q fashion-recomendation-dataset.zip -d .

"""##Cek apakah file 'fashion_metadata.csv' sudah ada"""

import os
print("File yang tersedia:", os.listdir())

"""## 4. Membaca file fashion_metadata.csv dengan Pandas"""

import pandas as pd

"""##MEMASTIKAN FILE TERBACA"""

try:
    df = pd.read_csv('fashion_metadata.csv')
    print("\nBerhasil membaca data!")
    print(df.head())
except FileNotFoundError:
    print("File tidak ditemukan. Cek kembali hasil print os.listdir()")

"""COBA BACA JUMLAH BAJU"""

# 1. Mengecek total baris data (asumsi 1 baris = 1 produk/baju)
print(f"Total data (baris): {len(df)}")

# 2. Mengecek apakah ada produk duplikat (berdasarkan ID atau Nama jika ada)
# Kita lihat dulu kolom apa saja yang ada
print("Nama Kolom:", df.columns)

# Jika ada kolom 'product_id' atau 'id', kita bisa hitung yang unik:
if 'product_id' in df.columns:
    print(f"Jumlah Baju Unik: {df['product_id'].nunique()}")
elif 'id' in df.columns:
    print(f"Jumlah Baju Unik: {df['id'].nunique()}")
else:
    # Jika tidak tau nama kolom ID-nya, kita cek dari nama produk
    # Ganti 'product_name' dengan nama kolom yang sesuai dari hasil print di atas
    # print(f"Jumlah Baju Unik: {df['product_name'].nunique()}")
    pass

# 3. Mengintip data lagi untuk memastikan
df.head()

"""##CEK TIPE DATA"""

# Melihat daftar kolom dan tipe datanya
df.info()

"""##AMBIL SAMPEL SAJA DATA TERLALU BANYAK"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# 1. Pastikan dataframe 'df' sudah ada (dari langkah import sebelumnya)
# Jika error, pastikan Anda sudah load data di langkah sebelumnya.
# Kita ambil sampel 10.000 data saja agar Colab tidak Crash (Out of RAM)
df_sample = df.head(10000).copy()

# 2. Seleksi Fitur (Feature Selection)
# Kita pilih kolom yang mendeskripsikan ciri-ciri baju
columns_to_use = ['gender', 'masterCategory', 'subCategory', 'articleType', 'baseColour', 'productDisplayName']

# Cek apakah kolom ada di data, jika tidak ada (beda versi dataset), kita sesuaikan
available_cols = [c for c in columns_to_use if c in df_sample.columns]
print(f"Kolom yang digunakan: {available_cols}")

# 3. Data Cleaning (Mengisi data kosong dengan string kosong)
for col in available_cols:
    df_sample[col] = df_sample[col].fillna('')

# 4. Membuat 'Soup' / 'Tags' (Menggabungkan semua fitur jadi satu kalimat)
def create_soup(x):
    return x['gender'] + ' ' + x['masterCategory'] + ' ' + x['subCategory'] + ' ' + x['articleType'] + ' ' + x['baseColour'] + ' ' + x['productDisplayName']

df_sample['tags'] = df_sample.apply(create_soup, axis=1)

# Lihat contoh hasil penggabungan
print("\nContoh Tags (Soup) untuk item pertama:")
print(df_sample['tags'].iloc[0])

"""##Modeling (TF-IDF & Cosine Similarity)"""

# 5. Inisialisasi TfidfVectorizer
# stop_words='english' akan membuang kata umum seperti 'and', 'the', 'is'
tfidf = TfidfVectorizer(stop_words='english')

# 6. Fit dan Transform data 'tags' menjadi matriks angka
tfidf_matrix = tfidf.fit_transform(df_sample['tags'])

print(f"\nUkuran Matriks TF-IDF: {tfidf_matrix.shape}")
# Output (10000, xxxx) artinya 10.000 barang dengan xxxx kata unik.

# 7. Menghitung Cosine Similarity
# Menghitung jarak antar vektor (semakin dekat = semakin mirip)
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

print("Matriks Kemiripan berhasil dibuat!")

"""##Membuat Fungsi Rekomendasi"""

# 8. Membuat Indexing
# Kita perlu cara untuk mencari index dataframe berdasarkan nama produk
indices = pd.Series(df_sample.index, index=df_sample['productDisplayName']).drop_duplicates()

def get_recommendations(title, cosine_sim=cosine_sim):
    # Cek apakah barang ada di data sampel
    if title not in indices:
        return "Barang tidak ditemukan di dalam sampel data (coba nama lain)."

    # Ambil index dari nama barang yang dicari
    idx = indices[title]

    # Ambil skor kemiripan dari semua barang dengan barang tersebut
    # list(enumerate(...)) membuat pasangan (index_barang, skor_kemiripan)
    sim_scores = list(enumerate(cosine_sim[idx]))

    # Urutkan barang berdasarkan skor kemiripan (dari tinggi ke rendah)
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Ambil 10 barang teratas (kecuali index 0 karena itu barang itu sendiri)
    sim_scores = sim_scores[1:11]

    # Ambil index barang-barang tersebut
    movie_indices = [i[0] for i in sim_scores]

    # Kembalikan nama-nama barangnya, termasuk 'subCategory'
    return df_sample[['productDisplayName', 'masterCategory', 'articleType', 'subCategory']].iloc[movie_indices]

"""Testing (Uji Coba)"""

# Cek dulu satu nama barang yang ada di data sampel untuk percobaan
sample_item = df_sample['productDisplayName'].iloc[1]
print(f"Mencari rekomendasi untuk: '{sample_item}'\n")

# Panggil fungsi rekomendasi
recommendations = get_recommendations(sample_item)
print(recommendations)

"""##Kode untuk Membuat Gambar Visualisasi (Jalankan di Colab"""

import matplotlib.pyplot as plt
import seaborn as sns

# Set style visualisasi
sns.set_style('whitegrid')

# 1. Visualisasi Master Category
plt.figure(figsize=(10, 5))
sns.countplot(y='masterCategory', data=df, order=df['masterCategory'].value_counts().index, palette='viridis')
plt.title('Jumlah Produk per Master Category')
plt.xlabel('Jumlah')
plt.ylabel('Kategori Utama')
plt.show()

# 2. Visualisasi Gender
plt.figure(figsize=(8, 5))
sns.countplot(x='gender', data=df, order=df['gender'].value_counts().index, palette='pastel')
plt.title('Distribusi Produk Berdasarkan Gender')
plt.xlabel('Gender')
plt.ylabel('Jumlah')
plt.show()

# 3. Visualisasi Top 10 Warna
plt.figure(figsize=(10, 5))
top_colors = df['baseColour'].value_counts().head(10).index
sns.countplot(y='baseColour', data=df[df['baseColour'].isin(top_colors)], order=top_colors, palette='magma')
plt.title('10 Warna Paling Dominan')
plt.xlabel('Jumlah')
plt.ylabel('Warna')
plt.show()

"""##MARTIK"""

# Fungsi untuk menghitung Precision@K berdasarkan kesamaan 'subCategory'
def calculate_precision(model_recommendations, actual_category):
    # Hitung berapa banyak rekomendasi yang subCategory-nya SAMA dengan input
    relevant_count = model_recommendations[model_recommendations['subCategory'] == actual_category].shape[0]

    # K adalah jumlah total rekomendasi (biasanya 10)
    k = model_recommendations.shape[0]

    precision = relevant_count / k
    return precision

# --- CONTOH PENGUJIAN OTOMATIS ---
# Ambil satu sampel produk (misal produk ke-0)
sample_idx = 9
sample_title = df_sample['productDisplayName'].iloc[sample_idx]
sample_category = df_sample['subCategory'].iloc[sample_idx]

print(f"Produk Input: {sample_title}")
print(f"Kategori Asli: {sample_category}")

# Dapatkan rekomendasi
recs = get_recommendations(sample_title)

if isinstance(recs, str): # Cek jika error/tidak ditemukan
    print(recs)
else:
    # Hitung presisi
    precision_score = calculate_precision(recs, sample_category)
    print(f"Precision@10: {precision_score * 100:.2f}%")

    # Tampilkan detail untuk verifikasi manual
    print("\nDetail Rekomendasi & Kategorinya:")
    print(recs[['productDisplayName', 'subCategory']])

"""##"""